version: '3'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
    command: [ "redis-server", "--requirepass", "$REDIS_PASSWORD" ]
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

volumes:
  redis-insight:

